export const domainOptions = [
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Machine Learning",
  "Artificial Intelligence",
  "Cyber Security",
  "Cloud Computing",
  "DevOps",
  "Blockchain",
  "UI/UX Design",
  "Game Development",
  "Internet of Things",
  "Software Testing",
  "Database Management",
  "Backend Development",
  "Frontend Development",
  "Full Stack Development",
  "Robotics",
  "Embedded Systems",
  "Network Engineering",
  "Business Analytics",
  "Product Management",
  "Digital Marketing",
  "Content Writing",
];
